version: '3.8'

services:
  dupligone-backend:
    build: ./dupligone-backend
    container_name: dupligone-backend
    ports:
      - "8080:8080"
    volumes:
      - ./dev_photos:/data/photos
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
      - rabbitmq
      - image-analyzer
  
  dupligone-frontend:
    build: ./dupligone-frontend
    container_name: dupligone-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost::8080
  
  image-analyzer:
    build: ./image-analyzer
    container_name: image-analyzer
    volumes:
      - ./dev_photos:/data/photos
    ports:
      - "5000:5000"
    
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      -  pg_data:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Messaging port
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
  
volumes:
  pg_data: